baseurl: / #/notes # the subpath of your site, e.g. /blog
url: https://notes.rigovanov.ru # the base hostname & protocol for your site
domain: notes.rigovanov.ru
permalink: /:categories/:title
lang: ru
# email: phil@rigovanov.ru
# author: Филипп Юрьевич Ригованов

title: Заметки
longtitle: Слаще мёда и капель сота
author:
  name: Филипп Юрьевич Ригованов # a1ip
  email: phil@rigovanov.ru
description: > # this means to ignore newlines until "show_excerpts:"
  Мои заметки при чтении Библии.  
  Я пользуюсь [этим планом чтения всей Библии](https://novchurch.github.io/today/plan) за год.
show_excerpts: false # set to true to show excerpts on the homepage

# disqus:
#   shortname: a1ip

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/img/card.png


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark # classic # solarized # solarized-dark # dark
  date_format: "%d/%m/%y" #"%D" #"%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/a1ip" }
    - { platform: twitter,        user_url: "https://twitter.com/phil_rigovanov" }
    - { platform: facebook,       user_url: "https://facebook.com/rigovanov" }
    - { platform: instagram,      user_url: "https://www.instagram.com/a1ip" }
    - { platform: keybase,        user_url: "https://keybase.io/a1ip" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/rigovanov" }
    # - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    - { platform: pinterest,      user_url: "https://www.pinterest.com/philrigovanov" }
    # - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    - { platform: telegram,       user_url: "https://t.me/rigovanov" }
    - { platform: youtube,        user_url: "https://www.youtube.com/philrigovanov" }
    - { platform: devto,          user_url: "https://dev.to/a1ip" }
    - { platform: dribbble,       user_url: "https://dribbble.com/a1ip" }
    - { platform: flickr,         user_url: "https://www.flickr.com/photos/a1ip" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: philipperigovanov
 
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - index.md
  - by-book.html
# - about.md

# Build settings
# theme: minima
remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [local]
